#!/bin/sh
# Sample service

start() {
echo "Started start service"
loadkmap < /etc/da.kmap
ifup wlan0
stty -F /dev/ttyS0 raw 9600 cs8 clocal -cstopb
/sbin/ip link set can0 up type can bitrate 500000
}

stop() {
echo "Stopped start service"
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit $?
